[server]
host="127.0.0.1"
port=8091

[database]
host="${DATABASE_HOST}"
user="${DATABASE_USER}"
password="${DATABASE_PASSWORD}"
name="${DATABASE_NAME}"
port=${DATABASE_PORT}
debug=${DATABASE_DEBUG}
ssl_mode="${DATABASE_SSL_MODE:-disable}"
max_open_conns=${DATABASE_MAX_OPEN_CONNS:-0}
max_idle_conns=${DATABASE_MAX_IDLE_CONNS:-0}
conn_max_lifetime_seconds=${DATABASE_CONN_MAX_LIFETIME_SECONDS:-0}

[logger]
level="debug"

[task]
list_default_limit=${TASK_LIST_DEFAULT_LIMIT:-20}
list_max_limit=${TASK_LIST_MAX_LIMIT:-50}

[team]
list_default_limit=${TEAM_LIST_DEFAULT_LIMIT:-10}
list_max_limit=${TEAM_LIST_MAX_LIMIT:-20}